config/routes.rb
DinnerTyme::Application.routes.draw do
  resources :ingredients

  resources :recipes

  resources :kitchens

  root :to => 'home#index'

end

app/models/ingredient.rb
# == Schema Information
#
# Table name: ingredients
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  photo      :string(255)
#  amount     :integer
#  unit       :string(255)
#  string     :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Ingredient < ActiveRecord::Base
  attr_accessible :amount, :name, :unit, :recipe_ids, :photo, :remote_photo_url
  has_and_belongs_to_many :recipes
  mount_uploader :photo, PhotoUploader
end

app/models/kitchen.rb
# == Schema Information
#
# Table name: kitchens
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  photo      :string(255)
#

class Kitchen < ActiveRecord::Base
  attr_accessible :name, :photo, :recipes, :recipe_ids, :remote_photo_url
  has_many :recipes
  mount_uploader :photo, PhotoUploader
end

app/models/recipe.rb
# == Schema Information
#
# Table name: recipes
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  photo      :string(255)
#  steps      :text
#  serves     :integer
#  rating     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Recipe < ActiveRecord::Base
  attr_accessible :name, :photo, :rating, :serves, :steps, :kitchen_id, :ingredient_ids, :remote_photo_url
  belongs_to :kitchen
  has_and_belongs_to_many :ingredients
  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end
  

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ingredients }
    end
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
    @ingredient = Ingredient.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ingredient }
    end
  end

  # GET /ingredients/new
  # GET /ingredients/new.json
  def new
    @ingredient = Ingredient.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ingredient }
    end
  end

  # GET /ingredients/1/edit
  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(params[:ingredient])

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render json: @ingredient, status: :created, location: @ingredient }
      else
        format.html { render action: "new" }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ingredients/1
  # PUT /ingredients/1.json
  def update
    @ingredient = Ingredient.find(params[:id])

    respond_to do |format|
      if @ingredient.update_attributes(params[:ingredient])
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy

    respond_to do |format|
      format.html { redirect_to ingredients_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/kitchens_controller.rb
class KitchensController < ApplicationController
  # GET /kitchens
  # GET /kitchens.json
  def index
    @kitchens = Kitchen.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @kitchens }
    end
  end

  # GET /kitchens/1
  # GET /kitchens/1.json
  def show
    @kitchen = Kitchen.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @kitchen }
    end
  end

  # GET /kitchens/new
  # GET /kitchens/new.json
  def new
    @kitchen = Kitchen.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @kitchen }
    end
  end

  # GET /kitchens/1/edit
  def edit
    @kitchen = Kitchen.find(params[:id])
  end

  # POST /kitchens
  # POST /kitchens.json
  def create
    @kitchen = Kitchen.new(params[:kitchen])

    respond_to do |format|
      if @kitchen.save
        format.html { redirect_to @kitchen, notice: 'Kitchen was successfully created.' }
        format.json { render json: @kitchen, status: :created, location: @kitchen }
      else
        format.html { render action: "new" }
        format.json { render json: @kitchen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /kitchens/1
  # PUT /kitchens/1.json
  def update
    @kitchen = Kitchen.find(params[:id])

    respond_to do |format|
      if @kitchen.update_attributes(params[:kitchen])
        format.html { redirect_to @kitchen, notice: 'Kitchen was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @kitchen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kitchens/1
  # DELETE /kitchens/1.json
  def destroy
    @kitchen = Kitchen.find(params[:id])
    @kitchen.destroy

    respond_to do |format|
      format.html { redirect_to kitchens_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recipes }
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/new
  # GET /recipes/new.json
  def new
    @recipe = Recipe.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/1/edit
  def edit
    @recipe = Recipe.find(params[:id])
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(params[:recipe])

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render json: @recipe, status: :created, location: @recipe }
      else
        format.html { render action: "new" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recipes/1
  # PUT /recipes/1.json
  def update
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      if @recipe.update_attributes(params[:recipe])
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def create_navlink(name, url)
    #<li class="active"><a href="#">Home</a></li>
    
    cname = name.downcase
    is_active = cname == controller.controller_name
    active = is_active ? "active" : ""
    
    link = link_to(name,url)
    "<li class='#{active}'>#{link}</li>".html_safe
  end
  
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/kitchens_helper.rb
module KitchensHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/home/index.html.erb
<div class = "hero-unit">
  <h1>DinnerTyme</h1>
  <small>...it's what's for dinner</small>
  <br><br>
<a class = "btn btn-primary btn-large" href ="/kitchens">Get started</a>
</div>

app/views/ingredients/_form.html.erb
<%= form_for @ingredient, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :photo, :class => 'control-label' %>
    <div class="controls">
    <%= f.file_field :photo %>
    | or enter remote URL: <%= f.text_field :remote_photo_url, :class => 'text_area span9' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :amount, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :amount, :class => 'number_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :unit, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :unit, :class => 'text_field' %>
    </div>
  </div>

  <div class="field">
    <div class="control-label">Choose recipes</div>
    <div class="controls">
      <% Recipe.all.each do |recipe| %>
        <%= check_box_tag 'ingredient[recipe_ids][]', recipe.id, @ingredient.recipes.include?(recipe) %>
        <%= recipe.name %>
        &nbsp;&nbsp;
      <% end %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                ingredients_path, :class => 'btn' %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<%- model_class = Ingredient -%>
<div class="page-header">
  <h2><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h2>
</div>

<%= render :partial => 'form' %>

app/views/ingredients/index.html.erb
<%- model_class = Ingredient -%>
<div class="page-header">
  <h2><%=t '.title', :default => model_class.model_name.human.pluralize %>&nbsp; &nbsp;

  <div class="btn-group">
    <button class="btn btn-primary">Create New</button>
    <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li><%= link_to 'Kitchen', new_kitchen_path %></li>
      <li class="divider"></li>
      <li><%= link_to 'Recipe', new_recipe_path %></li>
      <li class="divider"></li>
      <li><%= link_to 'Ingredient', new_ingredient_path %></li>
    </ul>
  </div></h2>
</div>

<%= render :partial => 'shared/ingredient', :collection => @ingredients, :as => :ingredient %>

<div class="clearfix"></div>

<div class="row-fluid form-actions">
  <%= link_to 'Create New Ingredient', new_ingredient_path, :class => 'btn btn-primary' %>
  &nbsp;&nbsp;
  <div class="btn-group">
    <button class="btn">See All</button>
    <button class="btn dropdown-toggle" data-toggle="dropdown">
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li><%= link_to 'Kitchens', kitchens_path %></li>
      <li class="divider"></li>
      <li><%= link_to 'Recipes', recipes_path %></li>  
    </ul>
  </div>
</div>

app/views/ingredients/new.html.erb
<%- model_class = Ingredient -%>
<div class="page-header">
  <h2><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h2>
</div>

<%= render :partial => 'form' %>

app/views/ingredients/show.html.erb
<%- model_class = Ingredient -%>
<div class="page-header">
  <h2><%=t '.title', :default => model_class.model_name.human %>: <strong><%= @ingredient.name %></strong>
  &nbsp;
  <%= link_to 'Back to All Ingredients', ingredients_path, :class => 'btn btn-mini' %>

  <%= link_to 'See All Recipes', recipes_path, :class => 'btn btn-mini' %></h2>
</div>

<%= render :partial => 'shared/recipe', :collection => @ingredient.recipes, :as => :recipe %>

<div class="clearfix"></div>

<div class="row-fluid form-actions">

  <div class="btn-group">
    <button class="btn btn-primary">Create New</button>
    <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li><%= link_to 'Kitchen', new_kitchen_path %></li>
      <li class="divider"></li>
      <li><%= link_to 'Recipe', new_recipe_path %></li>
      <li class="divider"></li>
      <li><%= link_to 'Ingredient', new_ingredient_path %></li>
    </ul>
  </div>
  &nbsp;
  <div class="btn-group">
    <button class="btn">See All</button>
    <button class="btn dropdown-toggle" data-toggle="dropdown">
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li><%= link_to 'Kitchens', kitchens_path %></li>
      <li class="divider"></li>
      <li><%= link_to 'Recipes', recipes_path %></li>
      <li class="divider"></li>
      <li><%= link_to 'Ingredients', ingredients_path %></li>
    </ul>
  </div>

</div>

app/views/kitchens/_form.html.erb
<%= form_for @kitchen, :html => { :multipart => true, :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :photo, :class => 'control-label' %>
    <div class="controls">
    <%= f.file_field :photo %>
    | or enter remote URL: Remote URL: <%= f.text_field :remote_photo_url, :class => 'text_area span9' %>
    </div>
  </div>

  <div class="field">
    <div class="control-label">Choose recipes</div>
    <div class="controls">
    <% Recipe.all.each do |recipe| %>
      <%= check_box_tag 'kitchen[recipe_ids][]', recipe.id, @kitchen.recipes.include?(recipe) %>
      <%= recipe.name %>
      &nbsp;&nbsp;
    <% end %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                kitchens_path, :class => 'btn' %>
  </div>
<% end %>

app/views/kitchens/edit.html.erb
<%- model_class = Kitchen -%>
<div class="page-header">
  <h2><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h2>
</div>
<%= render :partial => 'form' %>

app/views/kitchens/index.html.erb
<%- model_class = Kitchen -%>
<div class="page-header">
  <h2><%=t '.title', :default => model_class.model_name.human.pluralize %>&nbsp; &nbsp;

  <div class="btn-group">
    <button class="btn btn-primary">Create New</button>
    <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li><%= link_to 'Kitchen', new_kitchen_path %></li>
      <li class="divider"></li>
      <li><%= link_to 'Recipe', new_recipe_path %></li>
      <li class="divider"></li>
      <li><%= link_to 'Ingredient', new_ingredient_path %></li>
    </ul>
  </div></h2>
</div>

<% @kitchens.each do |kitchen| %>
  <div class = "kitchen_container">
    <h4><%= kitchen.name %></h4>

    <h4><%= link_to 'Show Recipes', kitchen, :class => 'btn btn-primary' %></h4>

    <%= image_tag(kitchen.photo.thumb.url) %>

    <h5><%= link_to t('.edit', :default => t("helpers.links.edit")), edit_kitchen_path(kitchen), :class => 'btn btn-mini btn-success' %>&nbsp;

        <%= link_to 'Delete', kitchen_path(kitchen), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger' %></h5>
  </div>
<% end %>

<div class="clearfix"></div>

<div class="row-fluid form-actions">
  <%= link_to 'Create New Kitchen', new_kitchen_path, :class => 'btn btn-primary' %>
  &nbsp;&nbsp;
  <div class="btn-group">
    <button class="btn">See All</button>
    <button class="btn dropdown-toggle" data-toggle="dropdown">
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li><%= link_to 'Recipes', recipes_path %></li>
      <li class="divider"></li>
      <li><%= link_to 'Ingredients', ingredients_path %></li>
    </ul>
  </div>
</div>

app/views/kitchens/new.html.erb
<%- model_class = Kitchen -%>
<div class="page-header">
  <h2><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h2>
</div>

<%= render :partial => 'form' %>

app/views/kitchens/show.html.erb
<%- model_class = Kitchen -%>
<div class="page-header">
  <h2><%=t '.title', :default => model_class.model_name.human %> Recipes: <strong><%= @kitchen.name %></strong>
  &nbsp;
  <%= link_to 'Back to All Kitchens', kitchens_path, :class => 'btn btn-mini' %>
  &nbsp;
  <%= link_to 'See All Recipes', recipes_path, :class => 'btn btn-mini' %></h2>
</div>

<%= render :partial => 'shared/recipe', :collection => @kitchen.recipes, :as => :recipe %>

<div class="clearfix"></div>

<div class="row-fluid form-actions">

  <div class="btn-group">
    <button class="btn btn-primary">Create New</button>
    <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li><%= link_to 'Kitchen', new_kitchen_path %></li>
      <li class="divider"></li>
      <li><%= link_to 'Recipe', new_recipe_path %></li>
      <li class="divider"></li>
      <li><%= link_to 'Ingredient', new_ingredient_path %></li>
    </ul>
  </div>
  &nbsp;
  <div class="btn-group">
    <button class="btn">See All</button>
    <button class="btn dropdown-toggle" data-toggle="dropdown">
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li><%= link_to 'Kitchens', kitchens_path %></li>
      <li class="divider"></li>
      <li><%= link_to 'Recipes', recipes_path %></li>
      <li class="divider"></li>
      <li><%= link_to 'Ingredients', ingredients_path %></li>
    </ul>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "DinnerTyme" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">DinnerTyme</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= create_navlink("Kitchens", kitchens_path)  %></li>
              <li><%= create_navlink("Recipes", recipes_path)  %></li>
              <li><%= create_navlink("Ingredients", ingredients_path)  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="container-fluid">
        <%= bootstrap_flash %>
        <%= yield %>
      </div>

      <footer class="container-fluid">
        <p>Ralph Bernardo's <em>Intro to Web Development</em> Final, General Assembly &copy; 2012</p>
      </footer>

    </div> <!-- main container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/recipes/edit.html.erb
<%- model_class = Recipe -%>
<div class="page-header">
  <h2><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h2>
</div>

<%= render :partial => 'form' %>

app/views/recipes/index.html.erb
<%- model_class = Recipe -%>
<div class="page-header">
  <h2><%=t '.title', :default => model_class.model_name.human.pluralize %>&nbsp; &nbsp;

  <div class="btn-group">
    <button class="btn btn-primary">Create New</button>
    <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li><%= link_to 'Kitchen', new_kitchen_path %></li>
      <li class="divider"></li>
      <li><%= link_to 'Recipe', new_recipe_path %></li>
      <li class="divider"></li>
      <li><%= link_to 'Ingredient', new_ingredient_path %></li>
    </ul>
  </div></h2>
</div>

<%= render :partial => 'shared/recipe', :collection => @recipes, :as => :recipe %>

<div class="clearfix"></div>

<div class="row-fluid form-actions">
  <%= link_to 'Create New Recipe', new_recipe_path, :class => 'btn btn-primary' %>
  &nbsp;&nbsp;
  <div class="btn-group">
    <button class="btn">See All</button>
    <button class="btn dropdown-toggle" data-toggle="dropdown">
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li><%= link_to 'Ingredients', ingredients_path %></li>
      <li class="divider"></li>
      <li><%= link_to 'Kitchens', kitchens_path %></li>
    </ul>
  </div>
</div>

app/views/recipes/new.html.erb
<%- model_class = Recipe -%>
<div class="page-header">
  <h2><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h2>
</div>

<%= render :partial => 'form' %>

app/views/recipes/show.html.erb
<%- model_class = Recipe -%>
<div class="page-header">
  <h2><%=t '.title', :default => model_class.model_name.human %> Ingredients: <strong><%= @recipe.name %></strong>
  &nbsp;
  <%= link_to 'Back to All Recipes', recipes_path, :class => 'btn btn-mini' %>

  <%= link_to 'See All Ingredients', ingredients_path, :class => 'btn btn-mini' %></h2>
</div>

<%= render :partial => 'shared/ingredient', :collection => @recipe.ingredients, :as => :ingredient %>

<div class="clearfix"></div>

<div class="row-fluid form-actions">

  <div class="btn-group">
    <button class="btn btn-primary">Create New</button>
    <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li><%= link_to 'Kitchen', new_kitchen_path %></li>
      <li class="divider"></li>
      <li><%= link_to 'Recipe', new_recipe_path %></li>
      <li class="divider"></li>
      <li><%= link_to 'Ingredient', new_ingredient_path %></li>
    </ul>
  </div>
  &nbsp;
  <div class="btn-group">
    <button class="btn">See All</button>
    <button class="btn dropdown-toggle" data-toggle="dropdown">
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li><%= link_to 'Kitchens', kitchens_path %></li>
      <li class="divider"></li>
      <li><%= link_to 'Recipes', recipes_path %></li>
      <li class="divider"></li>
      <li><%= link_to 'Ingredients', ingredients_path %></li>
    </ul>
  </div>

</div>

app/views/shared/_ingredient.html.erb
<div class = "ingredient_container">
  <sidebar>

    <h6><%= link_to t('.edit', :default => t("helpers.links.edit")), edit_ingredient_path(ingredient), :class => 'btn btn-mini btn-success' %>&nbsp;

    <%= link_to 'Delete', ingredient_path(ingredient), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger' %></h6>

    <h4><%= ingredient.name %></h4>

    <p><strong>Quantity:</strong> <%= ingredient.amount %> <%= ingredient.unit %></p>

  </sidebar>

  <%= image_tag(ingredient.photo.thumb.url) %>

  <h5><%= link_to 'Ingredient Found In Which Recipes?', ingredient, :class => 'btn' %></h5>

</div>

app/views/shared/_recipe.html.erb
<div class = "recipe_container span11">
    <sidebar>
      <h4><%= link_to 'Show Ingredients', recipe, :class => 'btn btn-primary' %></h4>

      <div class="image_container"><%= image_tag(recipe.photo.thumb.url) %></div>

    </sidebar>

  <h3><%= recipe.name %></h3>
  <br>
  <strong>Chef:</strong> <%= recipe.kitchen ? link_to(recipe.kitchen.name, kitchen_path(recipe.kitchen)) : link_to('Please enter kitchen', edit_recipe_path(recipe)) %> |
  <strong>Serves:</strong> <%= recipe.serves %> |
  <strong>Rating:</strong> <%= recipe.rating %>&nbsp;&nbsp;
  <h5><%= link_to ' Edit', edit_recipe_path(recipe), :class => 'btn btn-mini btn-success' %>&nbsp;

  <%= link_to ' Delete', recipe_path(recipe), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger' %></h5>
  <br><br>
  <%= recipe.steps.html_safe %>

</div>